### ISSUE TITLE
Всю логику взаимодействия с внешним API вынести в отдельный компонент

### ISSUE THREAD

**Issue by VitaliyNazarov** [victor-skalskiy/xproxy#3]
https://github.com/victor-skalskiy/xproxy/blob/afc5857cc463c7d79fc4897d2f179890770188d7/XProxy.Services/SettingsService.cs#L110-L128

1. Все аналогично предыдущему ищью: добавить интерфейс, реализацию, регистрацию в DI и инжекцию в сервис

**Comment by victor-skalskiy** [comment]
already fix
