### ISSUE TITLE
Все настройки урлов, и всяких параметров убрать из модели

### ISSUE THREAD

**Issue by VitaliyNazarov** [victor-skalskiy/xproxy#6]
https://github.com/victor-skalskiy/xproxy/blob/afc5857cc463c7d79fc4897d2f179890770188d7/XProxy.Domain/UserSettings.cs#L24-L28

Обо всех этих Http делах должен знать только тот сервис который взаимодействует с внешним сервисом. И если подразумевается что они могут измениться то вытащить в отдельную секцию в appsettings.json и прокинуть в http сервис.

**Comment by victor-skalskiy** [comment]
fix
